### ISSUE TITLE
Don't know how to build task 'ita:import' 

### ISSUE THREAD

**Issue by wajid626** [InternationalTradeAdministration/csl#39]
When i try import using the below command, i get the following error

bundle exec rake ita:import[ScreeningList::DplData]

Don't know how to build task 'ita:import' (See the list of available tasks with `rake --tasks`)

**Comment by jamesisaacs** [comment]
Hi @wajid626. Thanks for bringing this to our attention. I added a new task to import data locally and updated the README file.
